on:
  workflow_dispatch:

jobs:
  build:
    name: deploy to staging
    runs-on: ubuntu-22.04
    steps:
    - name: where i am?
      run: ls -la
    - name: building
      run: |
        ./build.sh
